FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
COPY bikeshare_model-0.0.1-py3-none-any.whl .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8001

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]