# python-package.yaml 
# This workflow will build docker image and deploys 
name: Python package 
on: 
  push: 
    branches: [ "main" ] 
  pull_request: 
    branches: [ "main" ]

jobs: 
  build: 
    runs-on: ubuntu-latest 
    strategy:
      fail-fast: false 
      matrix: 
        python-version: ["3.10"]
        
    steps:
    - uses: actions/checkout@v3 
    - name: Set up Python ${{ matrix.python-version }} 
      uses: actions/setup-python@v3 
      with:
        python-version: ${{ matrix.python-version }} 

    - name: Install build 
      run: | 
        python -m pip install --upgrade pip 
        pip install build 
    - name: build package 
      run: | 
        python -m build
    - name: copy whl file
      run: |
        cp bikeshare_project/dist/bikeshare_model-0.0.1-py3-none-any.whl bikeshare_project/bike_sharing_api/
    - name: build docker image
      run: | 
        docker build -t bikeshare-app .
    - name: docker up
      run: |
        docker-compose up

    
